replicaCount: 1

image:
  repository: gcr.io/cicd-458400/med-devops-app
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources: {}

metrics:
  enabled: true
  path: /metrics
  port: 8000