name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          project_id: cicd-458400

      - name: Authenticate Docker to GCR
        run: gcloud auth configure-docker --quiet

      - name: Build and Push Docker image
        run: |
          docker build -t gcr.io/cicd-458400/med-devops-app:v1 .
          docker push gcr.io/cicd-458400/med-devops-app:v1

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials dev-cluster \
            --zone us-central1-a --project cicd-458400

      - name: Deploy using Helm
        run: |
          helm upgrade --install med-devops-app ./helm/med-devops-app \
            --set image.repository=gcr.io/cicd-458400/med-devops-app \
            --set image.tag=v1